package com.peng.agent.client

data class AppConfig(
    val model: String = "deepseek-v4-flash",
    val apiBase: String = "https://api.deepseek.com/v1",
    val apiKey: String = "",
    val wsPort: Int = 18080,
    val workerModel: String = "",
    val workerApiBase: String = "",
    val workerApiKey: String = "",
    val maxTokens: Int = 4096,
    val temperature: Float = 0.7f,
    val topP: Float = 0.9f,
    val contextWindow: Int = 128000,
    val compressionThreshold: Float = 0.7f,
    val compressionStrategy: String = "summarize",
    val memorySearchLimit: Int = 5,
    val knowledgeSearchLimit: Int = 3,
    val knowledgeMaxDocs: Int = 0,
    val knowledgeMaxAgeDays: Long = 0L,
    val knowledgeAutoCleanup: Boolean = false,
    val maxTurns: Int = 50,
    val toolExecutionParallel: Boolean = true,
    val toolTimeoutSecs: Long = 30L,
    val streamTimeoutSecs: Long = 60L,
    val abortOnError: Boolean = false,
    val systemPrompt: String = "",
    val userName: String = "用户",
    val userStyle: String = "简洁",
    val visionApiKey: String = "",
    val visionApiBase: String = "https://open.bigmodel.cn/api/paas/v4",
    val visionModel: String = "glm-4.6v-flash",
    val bridgeUrl: String = ""
)
